// ============================================================
//  GlamBaddie.co — Catálogo de Productos (datos compartidos)
//  Usado por catalogo.js (tienda) y checkout.js (pago).
//  Añade nuevos productos aquí sin tocar el HTML.
// ============================================================

const PRODUCTOS = [
// =========================
// NUEVAS REFERENCIAS
// =========================
{ id:52, nombre:"Ancient Greece",       categoria:"lentes", precio:35000, descripcion:"Lente de contacto verde con degradado natural y textura suave. Diseño que aporta un brillo luminoso y elegante a la mirada.", especificaciones:["Color: Ancient Greece"], img:"Ancient-Greece.jpg", nuevo:true },
{ id:53, nombre:"Gullah Rome",          categoria:"lentes", precio:35000, descripcion:"Lente de contacto azul grisáceo con textura natural y acabado suave. Diseño que ilumina la mirada con un efecto fresco y sofisticado.", especificaciones:["Color: Gullah Rome"], img:"Gullah-Rome.jpg", nuevo:true },
{ id:8,  nombre:"Mermaid Green",        categoria:"lentes", precio:35000, descripcion:"Verde vibrante con degradado oscuro.", especificaciones:["DIA: 14.2mm","B.C: 8.5mm","Agua: 40%"], img:"mermaid-gree.jpg", video:"videos/mermaid-green.mp4", nuevo:false },
{ id:11, nombre:"Pola Green",           categoria:"lentes", precio:35000, descripcion:"Lente de contacto verde natural con acabado suave y luminoso. Ideal para un look fresco y vibrante.", especificaciones:["DIA: 14.2mm","B.C: 8.5mm","Agua: 40%"], img:"pola-green.jpeg", nuevo:false },
{ id:13, nombre:"Russian Grey",         categoria:"lentes", precio:35000, descripcion:"Lente de contacto gris azulado con matices verdes. Efecto místico y elegante para una mirada única e irresistible.", especificaciones:["DIA: 14.2mm","B.C: 8.5mm","Agua: 40%"], img:"Russian-Grey.jpg", nuevo:false },
{ id:14, nombre:"OMG Gray",             categoria:"lentes", precio:35000, descripcion:"Lente de contacto gris natural con aro oscuro pronunciado. Diseño EYESHARE que amplía y profundiza la mirada.", especificaciones:["DIA: 14.0mm","Agua: 38%"], img:"OMG-Gray.jpg", nuevo:false },
{ id:35, nombre:"Sydney Green",         categoria:"lentes", precio:35000, descripcion:"Lente de contacto verde azulado con degradado luminoso y aro definido. Diseño EYESHARE de uso anual que resalta la mirada con brillo natural.", especificaciones:["DIA: 14.2mm","Uso: 1 año"], img:"Sydney-Green.jpg", nuevo:false },
{ id:36, nombre:"Mirage Gray",          categoria:"lentes", precio:35000, descripcion:"Lente de contacto gris claro con efecto difuminado y aro oscuro pronunciado. Diseño elegante que ilumina y amplía la mirada.", especificaciones:["DIA: 14.2mm"], img:"Mirage-Gray.jpg", nuevo:false },
{ id:41, nombre:"Millennial Spice",     categoria:"lentes", precio:35000, descripcion:"Lente de contacto gris ahumado con textura sutil y acabado sofisticado. Diseño intenso que aporta profundidad y dramatismo a la mirada.", especificaciones:["Color: Millennial Spice"], img:"Millennial-Spice.jpg", nuevo:false },
{ id:42, nombre:"Buff Brown",           categoria:"lentes", precio:35000, descripcion:"Lente de contacto marrón cálido con textura natural y aro definido. Diseño que aporta profundidad y un brillo dorado sutil a la mirada.", especificaciones:["DIA: 14.2mm","B.C: 8.6mm","Agua: 38%","Uso: 6 meses"], img:"Buff-Brown.jpg", nuevo:false },
{ id:44, nombre:"Shadow Gray",          categoria:"lentes", precio:35000, descripcion:"Lente de contacto gris ahumado con aro oscuro pronunciado. Diseño elegante que profundiza y amplía la mirada con un efecto sofisticado.", especificaciones:["DIA: 14.2mm","B.C: 8.6mm","Agua: 38%","Uso: 6 meses"], img:"Shadow-Gray.jpg", nuevo:false },
{ id:45, nombre:"Brown Green",          categoria:"lentes", precio:35000, descripcion:"Lente de contacto verde oliva con base marrón y textura natural. Diseño OVOLOOK de uso semestral que aporta profundidad y un efecto cálido a la mirada.", especificaciones:["DIA: 14.2mm","G.DIA: 14.2mm","B.C: 8.6mm","Agua: 38%","Uso: 6 meses"], img:"Brown-Green.jpg", nuevo:false },
{ id:47, nombre:"Pattaya Blue",         categoria:"lentes", precio:35000, descripcion:"Lente de contacto azul grisáceo con textura natural y aro definido. Diseño UYAAI que aporta profundidad y un brillo suave a la mirada.", especificaciones:["Color: Pattaya Blue"], img:"Pattaya-Blue.jpg", nuevo:false },
{ id:48, nombre:"Insomnia Artist",      categoria:"lentes", precio:35000, descripcion:"Lente de contacto verde azulado con acabado luminoso y natural. Diseño Mill Creek que ilumina la mirada con un efecto fresco y cristalino.", especificaciones:["Color: Insomnia Artist"], img:"Insomnia-Artist.jpg", nuevo:false },
{ id:49, nombre:"Cloud Sun Brown",      categoria:"lentes", precio:35000, descripcion:"Lente de contacto marrón ámbar con degradado cálido y aro definido. Diseño OVOLOOK de uso semestral que aporta un brillo dorado natural a la mirada.", especificaciones:["DIA: 14.2mm","G.DIA: 13.4mm","B.C: 8.6mm","Agua: 38%","Uso: 6 meses"], img:"Cloud-Sun-Brown.jpg", nuevo:false },
{ id:50, nombre:"Richgirl Gray",        categoria:"lentes", precio:35000, descripcion:"Lente de contacto gris con base marrón y textura suave. Diseño EYESHARE que aporta un efecto natural y elegante a la mirada.", especificaciones:["DIA: 14.0mm","Agua: 40%"], img:"Richgirl-Gray.jpg", nuevo:false },
{ id:51, nombre:"Barbie Gray",          categoria:"lentes", precio:35000, descripcion:"Lente de contacto gris claro con acabado luminoso y aro suave. Diseño EYESHARE de uso anual que ilumina la mirada con un efecto claro y radiante.", especificaciones:["DIA: 14.2mm","Agua: 40%","Uso: 1 año"], img:"Barbie-Gray.jpg", nuevo:false },
];
